### ISSUE TITLE
Epic: UP Recursive Proofs

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#1098]
Tracking issue for exposing UltraPlonk's recursive proving function.

```[tasklist]
###### Pending
- [ ] https://github.com/noir-lang/acvm/issues/198
- [ ] https://github.com/AztecProtocol/barretenberg/issues/357
- [ ] https://github.com/AztecProtocol/barretenberg/pull/433
- [ ] https://github.com/AztecProtocol/barretenberg/pull/485
- [ ] https://github.com/noir-lang/noir/issues/1154
- [ ] https://github.com/noir-lang/acvm/pull/436
- [ ] https://github.com/noir-lang/noir/pull/1935
- [ ] https://github.com/AztecProtocol/barretenberg/pull/610
```

**Comment by Savio-Sou** [comment]
Refer to https://github.com/Savio-Sou/recursion-demo on how to make use of recursion.
