### ISSUE TITLE
Epic: SSA Refactoring

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#1376]
```[tasklist]
- [ ] https://github.com/noir-lang/noir/issues/758
- [ ] https://github.com/noir-lang/noir/issues/775
- [ ] https://github.com/noir-lang/noir/issues/785
- [ ] https://github.com/noir-lang/noir/issues/1118
- [ ] https://github.com/noir-lang/noir/issues/1119
- [ ] https://github.com/noir-lang/noir/issues/1120
- [ ] https://github.com/noir-lang/noir/issues/1121
- [ ] https://github.com/noir-lang/noir/issues/1167
- [ ] https://github.com/noir-lang/noir/issues/1212
- [ ] https://github.com/noir-lang/noir/issues/1300
- [ ] https://github.com/noir-lang/noir/issues/1307
- [ ] https://github.com/noir-lang/noir/issues/1410
- [ ] https://github.com/noir-lang/noir/issues/1411
- [ ] https://github.com/noir-lang/noir/issues/1412
- [ ] https://github.com/noir-lang/noir/issues/1413
- [ ] https://github.com/noir-lang/noir/issues/1414
- [ ] https://github.com/noir-lang/noir/issues/1416
- [ ] https://github.com/noir-lang/noir/issues/1420
- [ ] https://github.com/noir-lang/noir/issues/1425
- [ ] https://github.com/noir-lang/noir/issues/1427
- [ ] https://github.com/noir-lang/noir/issues/1431
- [ ] https://github.com/noir-lang/noir/issues/1438
- [ ] https://github.com/noir-lang/noir/issues/1439
- [ ] https://github.com/noir-lang/noir/issues/1441
- [ ] https://github.com/noir-lang/noir/issues/1442
- [ ] https://github.com/noir-lang/noir/issues/1443
- [ ] https://github.com/noir-lang/noir/issues/1444
- [ ] https://github.com/noir-lang/noir/issues/1445
- [ ] https://github.com/noir-lang/noir/issues/1446
- [ ] https://github.com/noir-lang/noir/issues/1447
- [ ] https://github.com/noir-lang/noir/issues/1451
- [ ] https://github.com/noir-lang/noir/issues/1452
- [ ] https://github.com/noir-lang/noir/issues/1458
- [ ] https://github.com/noir-lang/noir/issues/1467
- [ ] https://github.com/noir-lang/noir/issues/1469
- [ ] https://github.com/noir-lang/noir/issues/1473
- [ ] https://github.com/noir-lang/noir/issues/1478
- [ ] https://github.com/noir-lang/noir/issues/1479
- [ ] https://github.com/noir-lang/noir/issues/1486
- [ ] https://github.com/noir-lang/noir/issues/1487
- [ ] https://github.com/noir-lang/noir/issues/1497
- [ ] https://github.com/noir-lang/noir/issues/1500
- [ ] https://github.com/noir-lang/noir/issues/1502
```

**Comment by kevaundray** [comment]
Closing this as completed -- some of the issues have been branched out into separate non-blocking issues
