### ISSUE TITLE
Epic: Sandbox Noir

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#1378]
Noir release candidate with the smart contract syntaxes and functionalities for Aztec Sandbox.

```[tasklist]
- [ ] https://github.com/noir-lang/acvm/issues/297
- [ ] https://github.com/noir-lang/noir/issues/1377
- [ ] https://github.com/noir-lang/noir/issues/1016
- [ ] https://github.com/noir-lang/acvm/issues/197
- [ ] https://github.com/noir-lang/noir/issues/1156
- [ ] https://github.com/noir-lang/noir/issues/1168
```

**Comment by Savio-Sou** [comment]
#1156 will be repurposed into a more generalised (i.e. not Sandbox specific) feature. The rest of the issues have been completed.
