### ISSUE TITLE
LSP: Support Go To operations

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#1574]
### Problem

The LSP should support Go To operations as defined by the LSP specification
* [ ] Go To Declaration: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_declaration
* [ ] Go To Definition: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_definition
* [ ] Go To Type Definition: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_typeDefinition
* [ ] Go To Implementation: https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_implementation

### Happy Case

A user should be able to jump to various places in their code using the relevant LSP "Go To" action.

### Would you like to submit a PR for this Issue?

No

```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/issues/3657
- [ ] https://github.com/noir-lang/noir/issues/3706
- [ ] https://github.com/noir-lang/noir/issues/3707
- [ ] https://github.com/noir-lang/noir/issues/3719
- [ ] https://github.com/noir-lang/noir/issues/3720
- [ ] https://github.com/noir-lang/noir/issues/3721
- [ ] https://github.com/noir-lang/noir/issues/3723
- [ ] https://github.com/noir-lang/noir/issues/3724
- [ ] https://github.com/noir-lang/noir/issues/3725
- [ ] https://github.com/noir-lang/noir/issues/3726
- [ ] https://github.com/noir-lang/noir/issues/3727
- [ ] https://github.com/noir-lang/noir/issues/3728
- [ ] https://github.com/noir-lang/noir/issues/3729
- [ ] https://github.com/noir-lang/noir/issues/3730
- [ ] https://github.com/noir-lang/noir/issues/3942
- [ ] https://github.com/noir-lang/noir/issues/4090
```

**Comment by TomAFrench** [comment]
Closing as only a single issue remains.
