### ISSUE TITLE
Tracking issue: Fix remaining failing tests in the SSA Refactor

### ISSUE THREAD

**Issue by jfecher** [noir-lang/noir#1872]
### Aim

All tests in the old `test_data` folder should also compile with the SSA refactor.

### Expected Behavior

When compiling each test in `test_data` with the `--experimental-ssa` flag, they should all prove and verify.

### Bug

Instead, the following tests are still failing with the following reasons:

- [x] 9_conditional: `divide by zero` while proving (#1802)
- [x] array_dynamic: `expected array index to be a known constant`, requires dynamic array support in ACIR
- [ ] bit_shifts_runtime: (non-blocking) `not implemented: rhs must be a constant when doing a right shift`, requires dynamic shift support in ACIR
- [x] eddsa: hangs - EDIT: does not hang, just takes 16 minutes to complete...
- [ ] higher_order_functions: `lookup: variable not defined`, requires closure conversion, see #1254, and #1662
- [x] regression: `Error: could not satisfy all constraints` (#1800)

Please keep this list updated by checking each test once each bug is fixed and the test starts passing again. When all tests are passing we can close this issue.

**Comment by Savio-Sou** [comment]
Thanks Jake for creating the issue! Is the list of bugs up-to-date? cc @kevaundray 

P.S. feel free to make use of GitHub Tasklist if preferred:
```
> ```[tasklist]
> ### Tasks
> - [ ] Add a draft title or issue reference here
> ```
```

**Comment by dbanks12** [comment]
Watching this issue as it is blocking the "spending pending commitments" feature in Aztec. Wondering if this is quite a bit of work to do and what the timeline is for it?

**Comment by jfecher** [comment]
@dbanks12 this is a tracking issue for several smaller issues. Do you know which specifically is blocking?

**Comment by TomAFrench** [comment]
@jfecher All of them are :joy:. David is wanting us to switch over to the new SSA so we can start using the stepwise ACVM.

**Comment by kevaundray** [comment]
> @jfecher All of them are 😂. David is wanting us to switch over to the new SSA so we can start using the stepwise ACVM.

It would be:

- 9_conditional (Kev)
- **array_dynamic** (Guillaume)
-  **bit_shifts_runtime** (Guillaume)
-  regression (Maxim/Kev)
-  eddsa (Maxim/Kev)

With the ones in bold being the ones that are needed

**Comment by TomAFrench** [comment]
> **bit_shifts_runtime**

This shouldn't be a blocker for switching over as this is unimplemented in the old SSA as well afaik.

**Comment by jfecher** [comment]
I don't think `eddsa` should be a blocker either. It looks like it doesn't actually hang, but just takes 16 minutes to prove.

**Comment by kevaundray** [comment]
Closing this issue, the two remaining opened issues are not affected by this tracking issue. To track the status of bit shift runtime, see [here](https://github.com/noir-lang/noir/issues/1478)
