### ISSUE TITLE
Epic: E2E headless browser tests

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#2163]
```[tasklist]
### Prerequisites
- [ ] https://github.com/noir-lang/noir/issues/1229
- [ ] https://github.com/noir-lang/noir/issues/2251
- [ ] https://github.com/noir-lang/Planning/issues/28
- [ ] https://github.com/noir-lang/noir/issues/2610
- [ ] https://github.com/noir-lang/noir/issues/1244
- [ ] https://github.com/noir-lang/noir/pull/2763
- [ ] https://github.com/noir-lang/noir/issues/2694
```

The test suite should cover:

In CLI:
1. Compiling Noir programs into ACIRs with Nargo / noir_wasm (should be equivalent, up to engineering's recommendation)
2. Generate Solidity verifiers for the Noir programs with bb.js
3. Deploy the Solidity verifiers

In headless browser:

4. Generates witnesses with acvm_js
5. Prove the ACIRs + witnesses with bb.js
6. Submit proofs to the Solidity verifiers

## For discussion

1. What tests to include?

    Could be based on [`tooling/nargo_cli/tests`](https://github.com/noir-lang/noir/tree/8e93a5f4ccbcdb4fcd0f662d31ba4dd548aeae10/tooling/nargo_cli/tests)

2. Should we include downloading from npm in the test suite?

**Comment by kevaundray** [comment]
@kobyhallx who is owning this EPIC?
