### ISSUE TITLE
Epic: Testing (Noir programs) in IDE

### ISSUE THREAD

**Issue by phated** [noir-lang/noir#2441]
# Noir Testing

## Goals

We want Noir to have great end-to-end testing, including (but not limited to) unit tests, proving/verifying, integration tests. We also want to have common editor workflows in VSCode that people expect to support these features.

We already have some of these in the form of the `#[test]` attribute, the `> Run Test` code lens, and `Prover.toml` but we plan to tighten up the experience with additional initiatives.

```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/issues/2438
- [ ] https://github.com/noir-lang/vscode-noir/issues/33
- [ ] https://github.com/noir-lang/noir/issues/2222
- [ ] https://github.com/noir-lang/noir/issues/2442
```

**Comment by kevaundray** [comment]
Modified the title to clarify that we are talking about testing in Noir, ie Noir programs and not testing Noir ie the compiler

**Comment by LHerskind** [comment]
I think adding
- #1939
- #2484 

To this tracking issue would be useful.
