### ISSUE TITLE
Epic: Noir.js first release

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#2711]
```[tasklist]
### Prerequisite
- [ ] https://github.com/noir-lang/noir/issues/2163
```

As a Noir app developer, I would like to make use of **one** Noir.js package to carry out everything Noir-related in JavaScript environments, so I can worry less about importing and managing multiple packages and ease my coding.

The app development workflow would start in the CLI:

1. Compile Noir programs into ACIRs with Nargo
2. Generate Solidity verifiers for the Noir programs with Nargo
3. Deploy the Solidity verifiers with any preferred EVM tooling (e.g. hardhat, forge)

Then in browser, developers should be able to build their app where their users can:

4. **Install Noir.js to their project using NPM**
5. **Users can generate their desired set of inputs for the Noir program with the help of Noir.js**
6. **Generate witnesses with Noir.js**
7. Prove the ACIRs + witnesses with any Noir compatible proving backends' packages (e.g. barretenberg's bb.js)
8. Submit proofs to the Solidity verifiers with any preferred EVM tooling (e.g. ethers.js)

Note: This is meant to illustrate the E2E workflow for a Noir app developer. Noir.js's focus would be on **steps (4) to (6)** instead of all of the above.

```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/Planning/issues/31
- [ ] https://github.com/noir-lang/Planning/issues/32
- [x] NPM release for step (4): https://www.npmjs.com/package/@noir-lang/noir_js
- [ ] https://github.com/noir-lang/noir/issues/2738
- [ ] https://github.com/noir-lang/noir/issues/2819
- [ ] https://github.com/noir-lang/noir/issues/2821
- [ ] https://github.com/noir-lang/noir/issues/2836
- [ ] https://github.com/noir-lang/noir/issues/2838
- [ ] https://github.com/noir-lang/noir/pull/2902
- [ ] https://github.com/noir-lang/noir/pull/2920
- [ ] https://github.com/noir-lang/noir/pull/2921
- [ ] https://github.com/noir-lang/noir/pull/2922
- [ ] https://github.com/noir-lang/noir/issues/2930
- [ ] https://github.com/noir-lang/noir/issues/2881
- [ ] https://github.com/noir-lang/noir/issues/2882
- [ ] https://github.com/noir-lang/noir/issues/2945
- [ ] https://github.com/noir-lang/noir/issues/2946
- [x] [Clean up the old `@noir-lang/noir-ts` npm package](https://aztecprotocol.slack.com/archives/C04QF64EDNV/p1695392857853239?thread_ts=1695392765.955519&cid=C04QF64EDNV)
```

## Open to further discussions

Should we name it:
- **Noir.js** as it seems the most intuitive
- **Nargo.js** as parity with Nargo is largely what we're aiming for
  - An outlier would be [helper functions](https://github.com/noir-lang/noir/issues/2811) that could later be provided by this package but not necessarily provided by Nargo.
- Something else?

## Additional context

Developers might want to prove and verify Noir programs using the package as well, but as Noir is proving backend agnostic that would be left as proving backend packages' responsibilities (e.g. bb.js) for now.

We can revisit the need for tighter integration with backend packages at a later date.
