### ISSUE TITLE
Epic: Expose black box function solvers into TS

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#2811]
### Problem

Suggested by @Savio-Sou.

Developers who are making use of ACVM.js are often going to want to make use of the blackbox functions inside of their business logic. For instance pedersen commitments are used in applications such as [mastermind-noir](https://github.com/vezenovm/mastermind-noir/blob/43516b105294162522d4de24ebb7a31192fa99db/test/mm.ts#LL49C10-L49C10) and must be calculated in TS to feed into the circuit while matching a value calculated inside the circuit.

It's then important to provide an implementation which is guaranteed to be consistent with ACVM.

### Proposed solution

The ACVM.js can expose the implementations of black box functions as helper functions to allow developers query the result of these will be. They can then easily calculate any black box function like hashes (e.g. pedersen, keccak256) and verify signatures (schnorr, ecdsa).

This will be guaranteed to match the ACVM and prevent developers from having to hunt down TS implementations. 

```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/pull/2812
- [ ] https://github.com/noir-lang/noir/pull/3295
- [x] fixed_base_scalar_mul
- [ ] pedersen
- [ ] schnorr
- [ ] Export everything nicely from `noir_js` rather than just doing `import * as acvm from @noir-lang/acvm_js`
```

Rust solvers are available for `hash_to_field_128_security` and `fixed_base_scalar_mul` atm, so they should require less work than `pedersen` and `schnorr` to expose.

**Comment by kobyhallx** [comment]
It would be preferable to wait for improved Pedersen implementation to help others being implmented more easily.

**Comment by Savio-Sou** [comment]
> It would be preferable to wait for improved Pedersen implementation to help others being implmented more easily.

@kobyhallx for the Pedersen-based ones you meant (e.g. Merkle verification)? Or everything

**Comment by Savio-Sou** [comment]
Assigning `P-HIGH` to this Epic, as this helps the [Private Kernel Circuit rewrite project](https://github.com/AztecProtocol/aztec-packages/pull/2740).

**Comment by Savio-Sou** [comment]
@TomAFrench do you foresee https://github.com/noir-lang/noir/issues/3079 being able to execute the remaining black box functions / fully deprecate how we used to execute black box functions?

We can close this as superseded if yes.

**Comment by TomAFrench** [comment]
Closing as will be replaced with usage of bb.js in the short term

**Comment by Savio-Sou** [comment]
@TomAFrench is that something bb.js **already** or **should** offer?

**Comment by TomAFrench** [comment]
It does.
