### ISSUE TITLE
Epic: Profiler MVP

### ISSUE THREAD

**Issue by kobyhallx** [noir-lang/noir#2941]
## MVP Scope

It would be great to have a profiler that helps quickly estimate resource costs each line of a Noir program contributes, hence more easily optimizing proving performance of Noir programs.

The MVP user workflow should look something like:
1. Developer runs `nargo info --verbose`
2. Nargo prints # of ACIR opcodes associated with each line, e.g.
    ```
    fn main(x : Field) {
      foo(x) // -> 100 opcodes
      bar(x) // -> 200 opcodes
      let y = x + x; // -> 1 opcode
    }
    ```

```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/issues/2942
- [ ] https://github.com/noir-lang/noir/issues/3435
- [x] Expose it through Nargo
- [ ] https://github.com/noir-lang/noir/issues/3501
- [ ] https://github.com/noir-lang/noir/issues/3503
```

## Additional context - full vision

Not to be achieved with this Issue. More as extra context and for discussions where necessary.

The full vision could be:
1. VS Code extension always display the # of ACIR opcodes next to each line of Noir code
2. When the developer hovers over the #, it additionally displays:
    a. # of backend constraints
    b. Estimated proving time
    c. Estimated proving memory needs

Based on:
1. Developer's proving backend of choice
2. Developer's machine / simulated sample environment (e.g. Safari on iPhone 14)

**Comment by Savio-Sou** [comment]
Assigning `P-MEDIUM` as this greatly helps the [Private Kernel Circuit rewrite project](https://github.com/AztecProtocol/aztec-packages/pull/2740) and Noir gate golfers out there, but not necessarily blocking any works.

Guessing `E-MEDIUM`.
