### ISSUE TITLE
Epic: Complete Noir formatter implementation

### ISSUE THREAD

**Issue by f01dab1e** [noir-lang/noir#2993]
This is a tracking issue for the implementation of formatter.

- [x] Format Literal expressions.
- [x] Format BlockExpression expressions.
- [x] Format PrefixExpression expressions.
- [x] Format IndexExpression expressions.
- [x] Format CallExpression expressions.
- [x] Format MethodCallExpression expressions.
- [x] Format ConstructorExpression expressions.
- [x] Format MemberAccessExpression expressions.
- [x] Format CastExpression expressions.
- [x] Format InfixExpression expressions.
- [ ] Format IfExpression expressions.
- [ ] Format Variable expressions.
- [ ] Format Tuple expressions.
- [ ] Format Lambda expressions.
