### ISSUE TITLE
Epic: Implement Noir REPL-based debugger

### ISSUE THREAD

**Issue by mverzilli** [noir-lang/noir#3015]
### Problem

This is a tracking issue for the implementation of a REPL-based debugger for Noir.

This list will be updated/extended as we surface more features and/or necessary foundational work.

Any ideas and wants are welcome and can be considered, just comment here! :).

# Interactions
- [ ] Introduce new `nargo debug` command, which starts a REPL and allows ACVM opcode by opcode execution of a Noir program taking values specified in Prover.toml as inputs: #2995 
- [ ] Stepping through Noir expressions instead of ACVM opcodes
- [ ] Allow user to run functions from the debugger by manually entering inputs (instead of being limited to what's specified in Prover.toml)
- [ ] Debugger command to display witness map

# Information/Visualization
- [ ] Allow further inspection of runtime state: show registers, stacks, variable values, etc. (To be further fragmented)
- [ ] Display enough source code context to aid the user in debugging (at the moment of writing we are only displaying the exact location of the source code that corresponds to current execution step)

# Compiler/backend support
- [ ] Instrument the Brillig VM so that step-by-step debugging on it becomes possible
- [ ] Add mappings from witnesses to source code variable names

### Happy Case

Not sure I get this template field in this context :'( 

### Would you like to submit a PR for this Issue?

Maybe

**Comment by Savio-Sou** [comment]
Hi @mverzilli,

Welcome to the community and thank you for creating the Epic!

Would you prefer documenting and announcing from Noir's social media outlets:
- Each sub-feature merged (which helps garner community interests and contributions as we go), or
- When the Epic is completed?

Happy to support either way 🙌

**Comment by mverzilli** [comment]
Hi @Savio-Sou! I'm leaning towards _when the epic is completed_. Things are likely to change shape quickly as we grow the debugger at this phase, so early comms might confuse the community. I'll do my best to help this converge to a minimal first version in as much as a straight line as possible.

**Comment by mverzilli** [comment]
@Savio-Sou that said, I ultimately defer to your opinion! If you think it's a good idea to somehow share a sneak peek of this I'm open to it as well :)

**Comment by Savio-Sou** [comment]
@mverzilli thanks! Both approaches are very reasonable, simply making sure we are aligned on one 👍

**Comment by Savio-Sou** [comment]
On that note definitely feel free to share your WIP if you're attending Devconnect / doing any talks soon. No pressure to feel the need to "censor" / "remain in stealth" at all.

**Comment by mverzilli** [comment]
@Savio-Sou how do you usually handle these "umbrella" issues? The debugger MVP is now fully merged so I was considering closing this.
