### ISSUE TITLE
Epic: Refactor WASM libraries into component model

### ISSUE THREAD

**Issue by kobyhallx** [noir-lang/noir#3041]
## User Story

As a Product Owner 
I would like to build WASM libraries with component model
so that they can be easily consumed and integrated with other components and libraries on WASM layer.

## Additional Context

Noir's WASM stuff currently relies on wasm_bindgen, which is a piece of relatively outdated tooling.

Refactoring into a component model would describe components and functions in e.g. an IDL.

## Benefits

1. Wasm components can be used on their own within other wasm components/systems
2. There would be no wasm specific packages maintained, instead there would be descriptors of code specifying how to work with it.
3. Mitigates use of "stale" wasm tooling

```[tasklist]
### Tasks
- [ ] Refactor `noir_wasm`
- [ ] Refactory `acvm_js`
- [ ] Refactor `noirc_abi`
```

**Comment by Savio-Sou** [comment]
Assigning `P-LOW` for now as I'm unsure if this provides value to anyone immediately.

**Comment by kevaundray** [comment]
Closing as we do not plan to implement this for the foreseeable future
