### ISSUE TITLE
Epic: Add Noir function solvers into TS

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#3079]
In [Expose black box function solvers into TS#2811](https://github.com/noir-lang/noir/issues/2811) we exposed black box functions to typescript so that users can easily calculate values in the same way as which it will be calculated inside their circuits.

A number of useful functions are only implemented in Noir however, e.g. Poseidon, Sha256, etc. so we should expose methods to easily execute custom Noir programs and use their return values in user business logic.
```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/issues/3080
- [ ] https://github.com/noir-lang/noir/issues/3084
- [ ] https://github.com/noir-lang/noir/issues/3348
```

With https://github.com/noir-lang/noir/issues/3080 we can already achieve the funcitonality with `const { returnValue } = await new Noir(program_json).execute(inputs)`.

Outstanding tasks being:
- Replace the above JS snippet with a `const returnValue = executeCircuit(program_json, inputs)` syntax to be more functional
  - This requires the `executeSync` function to be added to acvm_js so we can execute ACIR without foreign calls in a sync fashion.
- Simplify generating a TS package from a Noir library
  - As the `execute` function can hardly match native TS packages in computation speeds given its ACVM overheads
  - Possible approaches could be
    - add a `#[codegen-ts]` attribute to mark a function as one to be compiled into a function for users to call.
    - codegen typesafe wrappers around `executeCircuit` which enforce type safety on the inputs.

**Comment by Savio-Sou** [comment]
As extra context, @kevaundray mentioned this would be helpful for https://github.com/AztecProtocol/aztec-packages/pull/2740.

**Comment by Savio-Sou** [comment]
Closing as completed as we do have `noir_codegen` now that largely if not fully fulfill this Issue's original purpose: https://noir-lang.org/docs/getting_started/tooling/noir_codegen
