### ISSUE TITLE
Create a Noir --> TypeScript codegen tool

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#3348]
### Problem

With https://github.com/noir-lang/noir/issues/3080 we have added the ability to `execute` Noir functions in TypeScript environments.

Problem is it hardly matches the speed with running native TS code given its ACVM overheads.

### Happy Case

We should create a tool for codegening arbitrary Noir functions into TS functions, where developers can then execute such functions natively in TS environments.

For first step, we would have:

```
// exports.nr

#[export]
unconstrained fn foo(x : u8)-> u8 {
   x
}
```

This would then make the bytecode for `foo` be available in a json file to b executed/simulated in typescript.

This becomes a lot nicer once we migrate and finalize our typescript wrapper for the json file which will automaticallt generate the typescript types.

```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/pull/3392
- [ ] https://github.com/noir-lang/noir/pull/3533
- [ ] https://github.com/noir-lang/noir/pull/3589
- [ ] https://github.com/noir-lang/noir/pull/3592
- [ ] https://github.com/noir-lang/noir/pull/3868
- [ ] https://github.com/noir-lang/noir/pull/3870
- [ ] https://github.com/noir-lang/noir/pull/3933
- [ ] https://github.com/noir-lang/noir/issues/4093
```

### Would you like to submit a PR for this Issue?

No

**Comment by Savio-Sou** [comment]
Updating to `E-HIGH` as we've already spent >1 week on the objective.

**Comment by TomAFrench** [comment]
> Problem is it hardly matches the speed with running native TS code given its ACVM overheads.

Just to be clear, this will have the exact same overheads as before. We're not transpiling ACIR into Javascript, just adding a more usable wrapper around it.

**Comment by Savio-Sou** [comment]
Assuming the technical scope was completed, we still need to document the feature.
