### ISSUE TITLE
Epic: Deprecate nested slices

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/noir#3363]
Handling for nested slices has already required a good amount of prep work but still has a few more tasks before it can be labelled fully complete.

The current status of nested slices is that a new pass has been introduced that fills nested slices with dummy data so that the internal types match up in size. The fill internal slices pass is necessary to get dynamic nested slices working in ACIR. This is the initial pass (https://github.com/noir-lang/noir/pull/3258). However, this pass currently only works with one block and needs to be expanded to handle filling of dummy data in flattening. I have made this task list to better track what issues are leftover to complete. 

#3187 is the initial work that prompted the fill internal slices pass.

```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/pull/3258
- [ ] https://github.com/noir-lang/noir/pull/3187
- [ ] https://github.com/noir-lang/noir/issues/3188
- [ ] https://github.com/noir-lang/noir/issues/3364
- [ ] https://github.com/noir-lang/noir/issues/2462
- [ ] https://github.com/noir-lang/noir/issues/2909
- [ ] https://github.com/noir-lang/noir/issues/3476
- [ ] https://github.com/noir-lang/noir/issues/3637
```

Ban nested slices tracker:
```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/issues/4017
- [ ] https://github.com/noir-lang/noir/issues/4019
- [ ] https://github.com/noir-lang/noir/issues/4020
```

As per this [comment](https://github.com/noir-lang/noir/issues/3363#issuecomment-1892690826) this is a following task list of any remaining slice issues that need to be resolved to state that slices are fully stable:
```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/issues/4202
- [ ] https://github.com/noir-lang/noir/issues/3687
- [ ] https://github.com/noir-lang/noir/issues/2540
- [ ] https://github.com/noir-lang/noir/issues/4220
- [ ] https://github.com/noir-lang/noir/issues/2535
```

There is also issue https://github.com/noir-lang/noir/issues/1344 for enabling printing of slices. This would be a more feature update and we might be able to tie into a general refactor of formatting strings in Noir.

**Comment by vezenovm** [comment]
After an internal meeting and the complexity introduced in https://github.com/noir-lang/noir/pull/3979 we have decied to temporarily shelve nested slices. Below is a separate tracklist on their temporary removal:

```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/issues/4017
- [ ] https://github.com/noir-lang/noir/issues/4019
```

**Comment by vezenovm** [comment]
I will leave https://github.com/noir-lang/noir/issues/528 to be closed once this issue is closed.

**Comment by vezenovm** [comment]
Closing this issue now that all tasks have been completed. Any new slice bugs can be separate from this issue.
