### ISSUE TITLE
Epic: Better GitHub Codespace Support

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#3623]
[GitHub Codespace](https://github.com/features/codespaces) is a useful tool for spinning up cloud development environment instances. This is particularly helpful for users that cannot / do not want to install anything locally (e.g. on mobile, on shared machines, first time users, Windows users without WSL, etc.), minimizing both onboarding and ocassionally development frictions.

This epic tracks the issues that get us automatic:

- Installation of the Noir VS Code extension
- Fetch and initialization of a docker instance with `noirup` and `nargo`

in Noir projects.

```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir-starter/issues/67
- [ ] https://github.com/noir-lang/noir-starter/issues/68
- [ ] https://github.com/noir-lang/noir/issues/3622
```
