### ISSUE TITLE
[TRACKING] Add Dockerfiles to replace Nix testing of Cargo / JS Packages on CI

### ISSUE THREAD

**Issue by sklppy88** [noir-lang/noir#3685]
```[tasklist]
### Tasks
- [ ] Docker file that builds nargo that we can add to the CI
- [ ] Docker file that builds js packages that we can add to the CI
- [ ] Docker file that tests nargo
- [ ] Docker file that js packages
- [ ] Caching in the CI of build layers across CI runs
- [ ] Investigate building and testing in the Mac environment (we may need to leave in the existing code for this, since docker doesn't support emulating Mac)
- [ ] Once we have CI working for docker with caching, remove the necessary components that we use nix for. (Main thing is the building, testing and publishing of js packages)
```
