### ISSUE TITLE
EPIC: Public VM

### ISSUE THREAD

**Issue by kevaundray** [noir-lang/noir#4033]
### Tracking tasks

- [x] #4158
- [x] #4159
- [x] #4160
- [x] #4369
- [ ] #4161
- [x] #4162
- [x] Support [SET opcode](https://yp-aztec.netlify.app/docs/public-vm/instructionset/#isa-section-set) – SET<size> (size: 8, 16, 32, 64, 128, not field). The SET opcode is currently being called Const in Brillig.
- [x] Add [CAST opcode](https://yp-aztec.netlify.app/docs/public-vm/instructionset/#isa-section-cast) that solely does type conversions
- [x] [JUMPIF](https://yp-aztec.netlify.app/docs/public-vm/instructionset/#isa-section-jumpi) to treat the conditional predicate as an integer and just check for zeroness instead of treating it a sa boolean
- [x] #4580
- [x] Convert signed division to unsigned arithmetic
- [ ] Compile all public functions in a contract into a single bytecode blob with a jump table

**Comment by TomAFrench** [comment]
> Add [CAST opcode](https://yp-aztec.netlify.app/docs/public-vm/instructionset/#isa-section-cast) that solely does type conversions

This is just #3946 and https://github.com/noir-lang/noir/pull/3997, right?
