### ISSUE TITLE
Docs snippet-ification

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#4174]
After #4164, we can now include code snippets from across the monorepo into the Noir docs. We've got a good amount of code-blocks in the docs which were copied across and so can be broken https://github.com/noir-lang/noir/issues/4172. We should push any code blocks out of the docs and into tests/examples for which correctness is enforced in CI.

```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/issues/4172
- [ ] Pull blackbox function signatures from stdlib definitions
- [ ] Move example usage of blackbox functions into `execution_success` tests.
- [ ] Pull Option<T> from stdlib
- [ ] Create concrete example projects for "Modules, Packages and Crates".
- [ ] Rework https://noir-lang.org/docs/dev/how_to/how-to-recursion to pull snippets from a concrete example
- [ ] Migrate ["Concepts"](https://noir-lang.org/docs/dev/noir/concepts/functions) over to pull from concrete example programs where possible.
- [ ] Migrate https://noir-lang.org/docs/dev/getting_started/hello_noir/project_breakdown to pull from a concrete example project
- [ ] Migrate https://noir-lang.org/docs/dev/getting_started/tooling/testing to pull from tests in the `noir_test_success` directory
```

**Comment by signorecello** [comment]
@jzaki this could be a good first issue in Noir docs if you happen to have the availability
