### ISSUE TITLE
LSP Refactoring Support

### ISSUE THREAD

**Issue by kobyhallx** [noir-lang/noir#4191]
```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/issues/4192
- [ ] https://github.com/noir-lang/noir/pull/5380
- [ ] https://github.com/noir-lang/noir/issues/5359
- [ ] https://github.com/noir-lang/noir/issues/5358
```
