### ISSUE TITLE
Epic: Folding

### ISSUE THREAD

**Issue by vezenovm** [noir-lang/noir#4426]
### Problem

With folding becoming a popular new recursion technique among SNARK proving systems we should implement a clean interface for backends to handle folding multiple ACIR function calls as they see fit.  

We currently inline all function calls in ACIR. We pass one ACIR blob to the backend essentially representing a single ACIR function. 

### Happy Case

ACIR/ACVM circuits should support multiple function calls that backends can implement how they see fit (either by folding or inlining those calls). 

```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/issues/4427
- [ ] https://github.com/noir-lang/noir/issues/4428
- [ ] https://github.com/noir-lang/noir/issues/4608
- [ ] https://github.com/noir-lang/noir/issues/4826
- [ ] https://github.com/noir-lang/noir/issues/4645
- [ ] https://github.com/noir-lang/noir/issues/4706
- [ ] https://github.com/noir-lang/noir/issues/4707
- [ ] https://github.com/noir-lang/noir/issues/4616
```

Nice to have:
```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/issues/4697
- [ ] https://github.com/noir-lang/noir/issues/4720
- [ ] https://github.com/noir-lang/noir/issues/4851
```

### Project Impact

Blocker

### Impact Context

This is needed for meaningfully fast client recursion by not only Aztec but any Noir program. Without folding backends can only implement vanilla IVC recursion which is significantly more expensive and restricts users. 

### Workaround

None

### Additional Context

Both issues #4427 and #4428 will most likely be implemented in https://github.com/AztecProtocol/aztec-packages as they are both breaking changes.

### Would you like to submit a PR for this Issue?

None

**Comment by vezenovm** [comment]
I am going to close #4851 nice-to-have list with the creation of https://github.com/noir-lang/noir/issues/4962. I wanted to check on removing #4720 as well. #4962 states we plan to remove `nargo info` entirely. Does this include for ACIR opcodes? Or do we expect an info command from the backend to include this as part of their report?

**Comment by TomAFrench** [comment]
I think that it makes sense to for the backend to return both the opcodes and constraints rather than trying to stitch them together from two different tools. Having a json response from the backend is the priority so we can maintain usage of the noir-gates-diff action but we'll need to have some form of report at some point.

**Comment by TomAFrench** [comment]
We can close #4851 but can you open an issue in aztec-packages for adding a human readable report for `bb gates`?

**Comment by vezenovm** [comment]
> We can close #4851 but can you open an issue in aztec-packages for adding a human readable report for `bb gates`?

Looks like you made it here https://github.com/AztecProtocol/aztec-packages/issues/6168?

**Comment by TomAFrench** [comment]
That's slightly different as I'm just wanting to get the JSON report as an MVP for this feature so we don't brick the github action. A human readable report can come in a separate PR imo.

**Comment by TomAFrench** [comment]
Feel free to tackle in the same PR if that's more convenient.

**Comment by vezenovm** [comment]
> A human readable report can come in a separate PR imo.

Ah I didn't see the distinction for human readable report I'll make a separate issue

**Comment by vezenovm** [comment]
Issue to replace #4720 can be found here (https://github.com/AztecProtocol/aztec-packages/issues/6190). Human readable report issue can be found here (https://github.com/AztecProtocol/aztec-packages/issues/6189)

**Comment by vezenovm** [comment]
All issues in this epic have been completed. If new bugs or features come up, they will be created as separate issues.
