### ISSUE TITLE
Epic: Add visibility system to hide implementation details internal to modules

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#4515]
### Problem

Currently all types/values defined in Noir are public, this causes an issue where libraries cannot provide a restricted interface as users can reach in an import internal implementation details.

### Happy Case

Noir should have a visibility system similar to Rust where by default functions, globals, traits, etc. are private to the modules they're defined in.

```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/issues/4775
- [ ] https://github.com/noir-lang/noir/pull/4491
- [ ] https://github.com/noir-lang/noir/issues/4837
- [ ] Switch warnings into errors
```

**Comment by Savio-Sou** [comment]
Good to close?

**Comment by TomAFrench** [comment]
The only remaining task is #6934 which is already part of the 1.0 milestone so we can close this.
