### ISSUE TITLE
Epic: Document how to document in `noir/docs/README.md`

### ISSUE THREAD

**Issue by Savio-Sou** [noir-lang/noir#4940]
### Problem

Our [docs README](https://github.com/noir-lang/noir/blob/8c89f042bef52a771c1a43731c9d5de69251e249/docs/README.md) hasn't been updated for a while.

During the period, we've introduced a number of scripts and tooling that improve our docs. Documenting how to utilize the features in the README would be great.

### Happy Case

```[tasklist]
### Tasks
- [ ] Document how to make retroactive changes to already versioned docs
- [ ] Document how to use https://github.com/noir-lang/noir/pull/3349/
- [ ] Document how to use https://github.com/noir-lang/noir/pull/4149/
- [ ] Document how is https://github.com/noir-lang/noir/actions/workflows/publish-docs.yml triggered and used
```

Feel free to convert the above into Issues.

### Project Impact

Nice-to-have

### Impact Context

Great for easing docs contributions.

### Workaround

None

### Would you like to submit a PR for this Issue?

None

**Comment by Savio-Sou** [comment]
@TomAFrench why are we closing this?
