### ISSUE TITLE
Epic: Rescope Nargo & NoirJS to exclude proving/verification/contract codegen

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#4960]
Nargo is currently the "everything-box" for working with Noir. You can install various proving backends, generate proofs in a single command, verify these, generate smart contract verifiers, etc. This has a few downsides:

- Once we take on most of the Noir workflow there's an expectation that we handle all of it. These leads to expectations such as
  - Handling inconsistencies with backends and external tools to solve QOL issues such as #1009, https://github.com/noir-lang/noir/issues/4476, https://github.com/noir-lang/noir/issues/4477
  - creating a "one-click" solution for generating recursive proof artifacts: https://github.com/noir-lang/noir/issues/4336
- As nargo is at once the compiler and proving interface, this pushes us towards a "source-code first" workflow where `nargo verify` will compile a circuit from scratch rather than just working on a verification key and a proof. Why should I need the original source code to verify a proof?

All this while providing a generic interface which can handle the peculiarities of many different proving backends.
  
Ideally Noir/Nargo should:
  - Specify the ACIR standard.
  - Specify a standard structure of a Noir project (so backends can make reasonable defaults for where to look  for compiled artifacts)
  - Compile Noir source code down to artifacts compliant with these two standards.
  - Provide tools for execution/testing/debugging of Noir source code.
  
  
As part of the tasks set out below we should:
- Ensure that the equivalent `bb` workflow works
- Make any necessary changes to `bb` such that the UX is still high.
- Add an equivalent test in CI using the `bb` workflow as an example

```[tasklist]
### Write a spec for ACIR backends to specify handling of
- [ ] ACIR Program artifacts
```

```[tasklist]
### Nargo
- [x] Remove `nargo codegen_verifier` command
- [x] Remove `nargo verify` command
- [x] Remove `nargo prove` command
- [ ] https://github.com/noir-lang/noir/issues/4962
- [x] Create replacement for `nargo info` to allow generation of reports similar to now.
- [x] Remove `nargo backend` command
- [ ] https://github.com/noir-lang/noir/issues/4961
```

```[tasklist]
### NoirJS
- [x] Remove concept of backends from `noir_js`
- [ ] https://github.com/noir-lang/noir/issues/5079
```

```[tasklist]
### Barretenberg feature parity tasks
- [ ] https://github.com/AztecProtocol/aztec-packages/pull/6283
- [ ] https://github.com/AztecProtocol/aztec-packages/pull/6320
- [ ] https://github.com/AztecProtocol/aztec-packages/pull/6321
```

**Comment by Savio-Sou** [comment]
From https://github.com/AztecProtocol/aztec-packages/pull/6320#issuecomment-2104676004:
> we should also expect that users should install their proving backend of choice rather than nargo acting as an installer for `bb`

@TomAFrench we shouldn't go that far as to remove default proving backend installation if that was what you were considering. That drives up onboarding frictions and support requests, with arguably little benefit in simplifying Noir 1.0's audit.

**Comment by TomAFrench** [comment]
Nargo is not going to be speaking to barretenberg and so there's no reason for it to install `bb`

**Comment by TomAFrench** [comment]
If we want `bb` to be a user facing component then it needs to have its own install method.

**Comment by Savio-Sou** [comment]
Oh I didn't mean Nargo specifically.

Goal is to preserve our current DevEx where users could get started / updated with 1 command.
If e.g. `noirup` automatically fetches the right version of `bb` that's a win.

**Comment by TomAFrench** [comment]
`noirup` is installation tooling for Nargo so it shouldn't install `bb`

**Comment by Savio-Sou** [comment]
Is there a good way to avoid / warn about `nargo` and `bb` version mismatches if they aren't pre-matched and installed as a batch?

**Comment by charlielye** [comment]
> Is there a good way to avoid / warn about `nargo` and `bb` version mismatches if they aren't pre-matched and installed as a batch?

The output artefacts of nargo could have a "backend api" version number associated with them.
If nargo bumps this number, it should bump it's major version number (breaking change), as it's changing the artefacts that it outputs such that they become incompatible with consumers of those artefacts.
bb can detect the mismatch and ask the user to upgrade, (knowing an upgrade will exist as there should always be a compatible bb). This bb release would also have a bumped major version number, as it's a breaking change regarding the artefacts it consumes.

In this model, noirs docs (which I think should at least give the 1-liner to install a compatible version of bb) can always provide, e.g. knowing compatibility with major version 3:
```
npm install --global bb.js@3
```

Also, I'm not totally against e.g. the `noirup` script offering to run the 1-liner or whatever is needed to upgrade a detected incompatible backend. As long as it's just scoped to a bit of bash in order to simplify...

**Comment by Savio-Sou** [comment]
> "backend api" version number

Including an ACIR version in Noir artifacts should do the trick 👍

**Comment by TomAFrench** [comment]
I'm going to close this epic and break out any remaining issues to be standalone or under a new documentation epic.

**Comment by Savio-Sou** [comment]
@TomAFrench SGTM 👍 would be great if you could remove unresolved Issues from the Epic body while recreating them separately for more accurate communications 🙌
