### ISSUE TITLE
[Tracking] Numeric Generics cleanup

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#6191]
```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/issues/6126
- [ ] https://github.com/noir-lang/noir/issues/6125
- [ ] https://github.com/noir-lang/noir/issues/6067
```

**Comment by TomAFrench** [comment]
Closing this as all sub issues are closed. @michaeljklein do you have anything else that you think should be covered by this issue?
