### ISSUE TITLE
[Tracking] stdlib cleanup + testing

### ISSUE THREAD

**Issue by TomAFrench** [noir-lang/noir#6193]
```[tasklist]
### Tasks
- [ ] https://github.com/noir-lang/noir/issues/6130
- [ ] https://github.com/noir-lang/noir/issues/4857
- [ ] https://github.com/noir-lang/noir/issues/4858
```

**Comment by Savio-Sou** [comment]
Duplicate of https://github.com/noir-lang/noir/issues/1258?
