### ISSUE TITLE
Epic: More modular frontend

### ISSUE THREAD

**Issue by michaeljklein** [noir-lang/noir#6569]
### Problem

The frontend could be split into more modular parts by reducing repetition, grouping some `Type` variants by their behavior, and splitting out some code into separate crates

#### Reduce repetition

- [ ] Use `NodeInterner` and `Type` `impl` helper functions (these functions are sometimes inlined)
- [ ] Use the same field names in the AST and HIR, e.g. `bounds` in `NoirTrait` vs. `trait_bounds` in `Trait`
- [ ] Use helper functions for `hir_def` fields and make them private, e.g. [`set_methods`](https://github.com/noir-lang/noir/blob/9db5937435200e90daa24267b19d3411eee0197d/compiler/noirc_frontend/src/hir_def/traits.rs#L151) for `Trait`, or else consider removing those helper functions

#### Grouping types by behavior

Each of the types in these groups shares methods, e.g. the sized container types all evaluate their lengths to `u32`'s, struct and tuple types both require iteration over their fields, etc.

- [ ] Sized container types:
  + `[T; N]`
  + `str<N>`
  + `fmtstr<N, T>`
- [ ] #6862
- [ ] #6798
  + `Field`
  + `bool`
  + `()`?
- [ ] Arithmetic generics:
  + `InfixExpr`
  + `CheckedCast`
  + `Constant`
- [ ] Type variables:
  + `TypeVariable`
  + `NamedGeneric`

#### Separate crates

- [ ] Make a crate for all integral binary operations, including evaluation, printing, etc. (used in resolution, arithmetic generics, `comptime` interpreter, `noirc_evaluator`, and possibly other locations)
- [ ] https://github.com/noir-lang/noir/issues/4852

### Workaround

None

### Project Impact

Nice-to-have

### Would you like to submit a PR for this Issue?

None

**Comment by michaeljklein** [comment]
FYI @TomAFrench
